apiVersion: ssmd.ssmd.io/v1alpha1
kind: Signal
metadata:
  labels:
    app.kubernetes.io/name: ssmd-operators
    app.kubernetes.io/managed-by: kustomize
  name: signal-sample
spec:
  # TODO(user): Add fields here
